import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthProvider";

const poppins = Poppins({
  variable: "--font-poppings",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Sistema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="pt-BR">
        <body
          className={`${poppins.variable} ${poppins.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
